--- #YAML:1.0
name:                Net-Amazon
version:             0.51
abstract:            Framework for accessing amazon.com via REST
license:             ~
author:              
    - Mike <m@perlmeister.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Digest::SHA:                   0
    Log::Log4perl:                 0.3
    LWP::UserAgent:                2
    Time::HiRes:                   1
    URI:                           0
    URI::Escape:                   0
    XML::Simple:                   2.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
