--- #YAML:1.0
name:                Net-Amazon
version:             0.40
abstract:            Framework for accessing amazon.com via REST
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Data::Dumper:                  0
    Log::Log4perl:                 0.3
    LWP::UserAgent:                2
    Time::HiRes:                   1
    URI:                           0
    XML::Simple:                   2.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike <m@perlmeister.com>
