# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Amazon
version:      0.21
version_from: lib/Net/Amazon.pm
installdirs:  site
requires:
    Data::Dumper:                  
    Log::Log4perl:                 0.3
    LWP::UserAgent:                2
    URI:                           
    XML::Simple:                   2.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
